const ADD_TO_LIST = 'ADD_TO_LIST';

const REMOVE_FROM_LIST = 'REMOVE_FROM_LIST';

const ADD_TASK = 'ADD_TASK';

const UPDATE_SELECTED_LIST_ID = 'UPDATE_SELECTED_LIST_ID';

const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';

const CHANGE_TASK_NAME = 'CHANGE_TASK_NAME';

const REMOVE_TASK = 'REMOVE_TASK';

export {ADD_TO_LIST , REMOVE_FROM_LIST , ADD_TASK , UPDATE_SELECTED_LIST_ID, CHANGE_TASK_NAME , CHANGE_TASK_STATUS, REMOVE_TASK }
